# GitHub Pages configuration for Amrudhya Harvests
title: "Amrudhya Harvests - Premium Indian Agricultural Exports"
description: "Harvesting India's Purity, Shipping to the World. Premium quality agricultural products from India."
url: "https://amrudhyaharvest.com"
baseurl: ""

# GitHub Pages settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
lang: en
author: Amrudhya Harvests
twitter:
  username: amrudhyaharvest
social:
  name: Amrudhya Harvests
  links:
    - https://wa.me/919106516439
    - https://www.linkedin.com/company/amrudhya-harvests/

# Exclude files from processing
exclude:
  - README.md
  - DEPLOYMENT.md
  - "*.zip"