# GitHub Pages configuration for AmrudhyaHarvest
title: "AmrudhyaHarvest - Premium Indian Agricultural Exports"
description: "Harvesting India's Purity, Shipping to the World. Premium quality agricultural products from India."
url: "https://amrudhyaharvest.com"
baseurl: ""
version: "v1"

# GitHub Pages settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
lang: en
author: AmrudhyaHarvest
twitter:
  username: amrudhyaharvest
social:
  name: AmrudhyaHarvest
  links:
    - https://wa.me/919106516439

# Exclude files from processing
exclude:
  - README.md
  - DEPLOYMENT.md
  - "*.zip"